### PR TITLE
Access to the encode/decode function From onPreExecute (1/2)

### PR DESCRIPTION
**Pull request by Ronan-Lenor**
Ah sorry, the 2 new function that i have provide recently can't be used in the onPreExecute Event.

So i had to entirely review the functionnality.

Now it is accessible on both onPreExecute & onPostExecute Event. AND it's much more easy to use.
As you don't have to provide the Request parameter in the method :P

### CODE REVIEW

**Comment by Ronan-Lenor** [comment]
part 2/2 : https://github.com/helios-ag/FMElfinderBundle/pull/173

**Comment by nicolasmure** [comment]
As there is already a public [`getVolume($hash)`](https://github.com/helios-ag/ElFinderPHP/blob/master/src/ElFinder.php#L413) function, I'd recommand to let the `volume` attribute protected and make a public `getVolumes()` function returning the `$volumes`.

**Comment by Ronan-Lenor** [comment]
The problem of using the `getVolume()` method, is that you need to provide the "encoded" volume id.
And i'm not sure that it make things more simple if in `encode($path)` you have to also provide the hash to get ..... a hash ^^;

**Comment by nicolasmure** [comment]
That was not my comment's purpose, I was talking about letting the `ElFinder::$volumes` attribute protected, and make an accessor to it :
```php
// ElFinder class
public function getVolumes()
{
    return $this->volumes;
}
```
rather than making the attribute pubic.
There is already a public way to access to a volume, and it's made by the `getVolume($hash)` function, that's why IMO it makes more sense to make such a `getVolumes()` function :wink: .

**Comment by helios-ag** [comment]
Agreed with getting volumes via getter.

**Comment by nicolasmure** [comment]
Sorry but I disagree with your last 3 commits. You're introducing BC breaks that way.
Actually, this PR should come down to having a public getter to the protected ElFinder::$volumes attribute. It's just one function to add, without editing anything else, you see ?

**Comment by Ronan-Lenor** [comment]
Yeah, i guess that drink Cognac and coding in same time a sunday afternoon is not what i'm doing the best :D 
it is corrected ;P

**Comment by nicolasmure** [comment]
:+1: :beers:

**Pull request closed without merging**
