### PR TITLE
Allow users to pass cmd's parameters (ex: upload_path) on a POST request

### PR DESCRIPTION
**Pull request by Ronan-Lenor**
as seen here https://github.com/helios-ag/ElFinderPHP/issues/29

### CODE REVIEW

**Comment by Ronan-Lenor** [comment]
hope to see it soon on the main branch soon. :P 
(so i can start to relax for the continuity of my development)

**Comment by nicolasmure** [comment]
I'm more in favor of [using a postExec event](https://github.com/helios-ag/ElFinderPHP/issues/29?_pjax=%23js-repo-pjax-container#issuecomment-149653048), but if this PR is accepted, please [update the doc](https://github.com/helios-ag/FMElfinderBundle/blob/master/README.md "README.md") to explain how to use custom parameters with a POST request.

**Comment by Ronan-Lenor** [comment]
Security fail on the post event. Anyway yes, if it's accepted, i will do my best to explain it clearly. (should be easy haha)

**Comment by nicolasmure** [comment]
[Subrequests](https://github.com/helios-ag/FMElfinderBundle/blob/master/README.md#sub-requests "Subrequests") will also become available with HTTP POST requests (ie with file upload) :sunglasses:

**Comment by nicolasmure** [comment]
seems ok :wink: 

:+1:

**Comment by helios-ag** [comment]
I'll test it today and tag.

**Pull request merged**
